Add additional semver validation

diff --git a/cli/Makefile.toml b/cli/Makefile.toml
--- a/cli/Makefile.toml
+++ b/cli/Makefile.toml
@@ -29,8 +29,14 @@ install_crate = { crate_name = "cargo-instruments", binary = "cargo", test_arg =
 [tasks.bump]
 description = "Bumps all packages to the specified version"
 dependencies = ["install-cargo-release", "install-sd"]
+script_runner = "zsh"
 script = '''
 VERSION=${@}
+if [[ "$VERSION" = -* ]] || [[ ! $(npx --yes semver $VERSION) ]];
+then
+  echo "'$VERSION' is invalid semver"
+  exit 1
+fi
 cargo release version $VERSION --execute --no-confirm
 cd npm/cli
 npm version --git-tag-version false $VERSION
